plugins {
    id 'java'
    id 'application'
}

group = 'com.aresstack'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    if (JavaVersion.current().isJava9Compatible()) {
        options.release.set(8)
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'org.java-websocket:Java-WebSocket:1.5.2'
    implementation 'org.slf4j:slf4j-api:1.7.32'
    runtimeOnly 'ch.qos.logback:logback-classic:1.2.13'
}

application {
    mainClassName = 'com.aresstack.keepassrpc.demo.KeePassRpcSettingsDemo'
}
