projectGroup=com.aresstack
projectVersion=0.1.0-beta.1
artifactId=keepassrpc-java

pomName=keepassrpc-java
pomDescription=Java/Swing integration for KeePassRPC pairing and configuration.
pomUrl=https://github.com/aresstack/keepassrpc-java
pomScmConnection=scm:git:https://github.com/aresstack/keepassrpc-java.git
pomScmDeveloperConnection=scm:git:ssh://git@github.com/AresStack/keepassrpc-java.git
pomScmUrl=https://github.com/aresstack/keepassrpc-java
pomDeveloperId=aresstack
pomDeveloperName=AresStack

org.gradle.jvmargs=-Dfile.encoding=UTF-8
